name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t vite-app .

      - name: Save Docker image as a tar file
        run: |
          docker save -o /tmp/vite-app.tar vite-app

      - name: Check tar file permissions
        run: |
          ls -lah /tmp/vite-app.tar
          chmod +r /tmp/vite-app.tar  # Ensure read permissions

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}  # EC2 instance IP
          username: ${{ secrets.VM_USER }}  # EC2 username
          key: ${{ secrets.VM_SSH_KEY }}  # SSH private key
          source: "/tmp/vite-app.tar"
          target: "~/"

      - name: SSH into EC2 and deploy the Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker load -i ~/vite-app.tar  # Load the Docker image on EC2
            docker stop vite-container || true  # Stop running container (if exists)
            docker rm vite-container || true  # Remove stopped container
            docker run -d -p 80:80 --name vite-container vite-app  # Start new container
