name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # This is where the workflow runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t vite-app .

      - name: Save Docker image as a tar file
        run: |
          docker save -o vite-app.tar vite-app

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}  # EC2 instance IP
          username: ${{ secrets.VM_USER }}  # EC2 username (e.g., 'ec2-user' or 'ubuntu')
          key: ${{ secrets.VM_SSH_KEY }}  # EC2 SSH key
          source: "vite-app.tar"
          target: "~/"

      - name: SSH into EC2 and deploy the Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker load -i ~/vite-app.tar  # Load the Docker image on EC2
            docker stop vite-container || true  # Stop any existing container (if running)
            docker rm vite-container || true  # Remove the stopped container (if exists)
            docker run -d -p 80:80 --name vite-container vite-app  # Run the new container in detached mode
