name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Connection
      run: |
        echo "$VM_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: Copy Project Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -r . $VM_USER@$VM_IP:/home/$VM_USER/app

    - name: SSH into EC2 and Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem $VM_USER@$VM_IP << 'EOF'
          cd /home/$VM_USER/app
          
          # Stop and remove the existing container
          docker stop myapp || true
          docker rm myapp || true

          # Build and start a new container
          docker build -t myapp .
          docker run -d -p 3000:3000 --name myapp myapp
        EOF
