name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and save Docker image
        run: |
          docker build -t vite-app .
          mkdir -p /tmp/docker
          docker save vite-app > /tmp/docker/vite-app.tar
          ls -lah /tmp/docker/vite-app.tar
          chmod 644 /tmp/docker/vite-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "/tmp/docker/vite-app.tar"
          target: "/home/${{ secrets.VM_USER }}"
          strip_components: 2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker load -i ~/vite-app.tar
            docker stop vite-container || true
            docker rm vite-container || true
            docker run -d -p 80:80 --name vite-container vite-app