name: Deploy Code to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts

      # Step 3: Copy the code to VM
      - name: Copy code to VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          scp -i ~/.ssh/id_rsa -r . ${VM_USER}@${VM_IP}:/home/${VM_USER}/deployment/

      # Step 4: SSH into VM, build and run the Docker container
      - name: Build and run Docker container
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          ssh -i ~/.ssh/id_rsa ${VM_USER}@${VM_IP} << 'EOF'
          cd /home/${VM_USER}/deployment
          echo "Stopping and removing existing containers..."
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true
          echo "Building Docker image..."
          sudo docker build -t react-vite-app .
          echo "Running Docker container..."
          sudo docker run -d -p 5173:5173 --name react-vite-app react-vite-app
          EOF